// Mock data for demonstration
const MOCK_TASKS = [
  {
    id: '1',
    title: 'Follow up on Smith & Co. late filing',
    type: 'Follow-up',
    dueDate: '2025-04-23',
    amount: 12500,
    priority: 'high',
    status: 'pending',
  },
  {
    id: '2',
    title: 'Review Johnson Property tax assessment',
    type: 'Review',
    dueDate: '2025-04-24',
    amount: 8750,
    priority: 'medium',
    status: 'pending',
  },
  {
    id: '3',
    title: 'Process ABC Corp quarterly payment',
    type: 'Payment',
    dueDate: '2025-04-21',
    amount: 45000,
    priority: 'high',
    status: 'pending',
  },
  {
    id: '4',
    title: 'Send reminder to XYZ LLC',
    type: 'Reminder',
    dueDate: '2025-04-25',
    amount: 5200,
    priority: 'medium',
    status: 'pending',
  },
  {
    id: '5',
    title: 'Audit Global Enterprises filings',
    type: 'Audit',
    dueDate: '2025-04-30',
    amount: 67800,
    priority: 'low',
    status: 'pending',
  },
  {
    id: '6',
    title: 'Update City Development tax records',
    type: 'Update',
    dueDate: '2025-04-22',
    amount: 23400,
    priority: 'high',
    status: 'complete',
  },
  {
    id: '7',
    title: 'Schedule meeting with delinquent taxpayers',
    type: 'Meeting',
    dueDate: '2025-04-29',
    amount: 34250,
    priority: 'medium',
    status: 'complete',
  },
];